// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Toeicking2021.Data;

namespace Toeicking2021.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210325061729_AddSenetenceTableClassModified")]
    partial class AddSenetenceTableClassModified
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Toeicking2021.Models.Administrator", b =>
                {
                    b.Property<int>("AdministratorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Authcode")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool?>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("ResetPasswordCode")
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("AdministratorId");

                    b.ToTable("Administrators");
                });

            modelBuilder.Entity("Toeicking2021.Models.Sentence", b =>
                {
                    b.Property<int>("SentenceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("date");

                    b.Property<string>("Chinesese")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<string>("GrammarCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sen")
                        .IsRequired()
                        .HasColumnType("nvarchar(600)");

                    b.Property<bool?>("Synonym")
                        .HasColumnType("bit");

                    b.Property<bool?>("WordOrigin")
                        .HasColumnType("bit");

                    b.HasKey("SentenceId");

                    b.ToTable("Sentences");
                });
#pragma warning restore 612, 618
        }
    }
}
